config/routes.rb
Portfolio::Application.routes.draw do
  resources :comments
  resources :posts
  resources :clients
  resources :sessions, :only => [:new, :create, :destroy]
  resources :contacts, :only => [:new, :create]

  match '/signup',  :to => 'clients#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/webhome',  :to => 'pages#webhome'
  match '/musichome',  :to => 'pages#musichome'
  match '/admin',	:to => 'pages#admin'
  match '/articles', :to => 'pages#articles'
  match '/news', 	:to => 'pages#news'
  match '/about',   :to => 'pages#about'
  match '/resume',   :to => 'pages#resume'
  match '/projects',    :to => 'pages#projects'
  match '/skills', 		:to => 'pages#skills'
  match '/resources', 	:to => 'pages#resources'
  match '/tutorials', 	:to => 'pages#tutorials'
  match '/help',    :to => 'pages#help'
  match '/contacts', :to => 'contacts#new'


  root :to => 'pages#webhome'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> 
        prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
        from being saved:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


app/views/shared/_login.html.erb
<h4>Client Login:</h4>

<%= form_for(:session, :url => sessions_path) do |f| %>
  <div class="field">
    <%= f.label : %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Sign in" %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
		<nav>
          <ul>
			<li><%= link_to 'Home', webhome_path, :class => is_active?(webhome_path) %></li>
		   <li><%= link_to "About", about_path, :class => is_active?(about_path) %></li>
	      <li><%= link_to "Contact", contacts_path, :class => is_active?(contacts_path) %></li>
			<li><%= link_to "Resume", resume_path, :class => is_active?(resume_path) %></li>
			<li><%= link_to "Projects", projects_path, :class => is_active?(projects_path) %></li>			
          </ul>
        </nav>	

app/views/shared/_search_bar.html.erb
<%= form_tag(search_path, :method => "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>