config/routes.rb
Portfolio::Application.routes.draw do
  resources :comments
  resources :posts
  resources :clients
  resources :sessions, :only => [:new, :create, :destroy]
  resources :contacts, :only => [:new, :create]

  match '/signup',  :to => 'clients#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/webhome',  :to => 'pages#webhome'
  match '/musichome',  :to => 'pages#musichome'
  match '/admin',	:to => 'pages#admin'
  match '/articles', :to => 'pages#articles'
  match '/news', 	:to => 'pages#news'
  match '/about',   :to => 'pages#about'
  match '/resume',   :to => 'pages#resume'
  match '/projects',    :to => 'pages#projects'
  match '/skills', 		:to => 'pages#skills'
  match '/resources', 	:to => 'pages#resources'
  match '/tutorials', 	:to => 'pages#tutorials'
  match '/help',    :to => 'pages#help'
  match '/contacts', :to => 'contacts#new'


  root :to => 'pages#webhome'

end

app/views/pages/about.html.erb
<%= render 'layouts/webhome' %>
<div class="leftCol">
	<div class="aboutText">
		<h3>"I Am What I Am"</h3>
		<p>Mark Howard aka howie born is a web designer, developer and programmer. </p>
		<p>I Studied Information Technology majoring in Information Systems at the University of Queensland. </p>
		<p>If i'm not solving web design problems or reading about new and creative ideas and techniques, 
		then you can usually find me strumming away on my guitar or making loops on my computer. </p>
		<p>I also love spending time outdoors doing some form of sporting activity, surfing, snowboarding, etc. 
		Not too big into watching TV, but would rather chat to mates or read a good book. </p>
	</div>
	  <div class="interestList">		<h3>Interests</h3>				<ul>
			<li>Snowboarding, surfing, pretty much most sports.</li>
			<li>Guitar</li>
			<li>Reading</li>
			<li>Architectural Design</li>
			<li>Travelling</li>
			<li>Web Surfing</li>
			<li>Most Things to do with Computers</li>
			</ul>
	  </div>
</div>




app/views/pages/admin.html.erb
<h2>@heading</h2>
<div class="adminActions">
<h3>Actions:</h3>
<strong>Client:</strong><br>
<ul>
	<li><%= link_to "Create client profile (Sign Up)(Admin only)", signup_path %></li>
	<li><%= link_to "Show client details (client & admin only)" %></li>
	<li><%= link_to "Edit client profile (admin only)" %></li>
	<li><%= link_to "Remove client profile (admin only)" %></li>
	<li><%= link_to "index all clients (admin only)" %></li>
</ul>
<br>
<strong>Posts</strong><br>
<ul>
	<li><%= link_to "Create Newspost/Blog (admin only)" %></li>
	<li><%= link_to "Edit Newspost/Blog (admin only)" %></li>
	<li><%= link_to "Show newspost/Blog" %></li>
	<li><%= link_to "index all newspost/Blog" %></li>
	<li><%= link_to "remove newspost/Blog (admin only)" %></li>
</ul>
<br>
<strong>Articles</strong>
	<ul>
	<li><%= link_to "Create Article (opens wizard)(admin only)" %></li>
	<li><%= link_to "Article Wizard (admin only)" %></li>
		<ul>
		  <li><%= link_to "Create header" %></li>
		  <li><%= link_to "Add Paragraph" %></li>
		  <li><%= link_to "Create header" %></li>
		</ul>
	<li><%= link_to "Remove Article (admin only)" %></li>
	<li><%= link_to "View Article" %></li>
	<li><%= link_to "edit article (admin only)" %></li>
	</ul>
Resume
Resources


		<ul>
		  <li><%= link_to "Create Client Profile", signup_path %></li>
		  <li><%= link_to "View All Clients", 'clients/index' %></li>
		  <li><%= link_to "Change Client Details", 'clients/edit' %></li>
		</ul>
	</div>

app/views/pages/help.html.erb

<h3>Website Construction Helper</h3>
<nav class="round">
  <ul>
    <li><%= link_to "Checklist", help_path(:anchor => "checklist")%>
    <li><%= link_to "Style Guide", help_path(:anchor => "style")%>
	<li><%= link_to "Navigation", help_path(:anchor => "nav")%>
	<li><%= link_to "Data Models", help_path(:anchor => "datamodels")%>
	<li><%= link_to "Model Relationships", help_path(:anchor => "modelrel")%>
  </ul>
</nav>
<h3><a name="checklist">Checklist</a></h3><br>
<ul>
<li>Complete Home Page</li>
	<ul>
	  <li>Add client login box</li>
	  <li>Write 300 words on Purpose/Mission, About Yourself, Web design etc.</li>
	  <li>Complete Homepage content.</li>
	  <li>Complete Images</li>
	  <li>Complete Links</li>
	  <li>Complete Path login as admin_user</li>
	  <li>Complete Path login as client<li>
	</ul>
<li> PAGE: page_name</li>
	<ul>
	  <li>Address Feature: (example)</li>
	  <li>Write content</li>
	  <li>Complete links</li>
	  <li>Images</li>
	</ul>
	  
</ul>

<h3><a name="style">Style Guide</a></h3>
<p>
<h4>COLORS :</h4>
<br>
3399cc - Ocean Blue<br>
333333 - Almost Black<br>
6666cc - Light Violet<br>
00cccc - Turquoise<br>
33cc99 - Dark Aqua<br>
FFFF99 - Creamy Yellow<br>
FF6600 - Bright Orange<br>
003399 - Nice velvet blue<br>
</p>
<p>
<br>
<h5>Navigation</h5>
<br>
MENU ITEMS<br>
 - Who we Are<br>
 - What We Do<br>
 - How We Work<br>
 - Get In Touch<br>
</p>
<br>
<h5><a name="datamodels">Data Models</a></h5>
<br>
<p>
DATA MODEL	for News
	- id
	- title
	- body
	- created_at
	- updated_on
	- 
</p>			
DATA MODEL for Post
	- id			(Primary Key, auto_increment)
	- title
	- body
	- type
	- created_at
	- updated_on
	
DATA MODEL for Article
	- id
	- title
	- author
	- 
	
<br>
<p>
<h5><a name="modelrel">Model Relationships</a><h5><br>

Actor --> Admin<br>
Actor --> Clients<br>
<br>

Process --> <strong>Admin</strong> > Log in > All Access Granted > Admin Home > @CRUD Resume > Log out<br>
															 > @CRUD Clients<br>
															 > @CRUD News<br>
															 > @CRUD Articles<br>
															 > @CRUD Resources<br>
															 > @CRUD Tutorials<br>
															 > @Projects<br>
															 > @Skills<br>
															 > @CheckStats<br>
															 > @Maintenance<br>
															 > @ViewSite<br>
<br>
Process --> <strong>Clients</strong> > View Site #Restricted > View News<br>
											> View Articles<br>
											> View Resources<br>
											> View Tutorials<br>
											> View About<br>
											> View Contact<br>
					> Log In > Extra access > View Projects<br>
										    > View Resume<br>
											> View Skills<br>
					
Relationships:<br>
Only 1 client can be Admin.<br>
News has many comments<br>
articles has many comments<br>


app/views/pages/musichome.html.erb
THIS PAGE IS STILL UNDER CONSTRUCTION!!!!

app/views/pages/projects.html.erb
<%= render 'layouts/webhome' %>

<ul id="slider1">
  
    <li>
      <div id="projectName"><h3>Boydsprattgolfwear - Site Redesign</h3></div>
		<div id="projectImage"><%= image_tag("noimage.gif", :alt => "No Image Available", :height => "200px") %></div>
		<div id="projectInfo">
			Boydsprattgolfwear is a small business that has been selling golf clothing and accessories. Due to recent expansion and increased sales
			the website for this company also needs to be upgraded. I have developed an ecommerce site using ruby on rails. The site is 
			designed to be simple and easy to use. This site has been changed to provide more administration functionality. It has also been
			redesigned to provide a customer base and inventory management.		
		</div>
    </li>
    
    <li>
	 	<div id="projectName"><h3>Boydsprattgolfwear - e-commerce website design</h3></div>
		<div id="projectImage"><%= image_tag("boyds-site-1.png", :alt => "No Image Available") %></div>
		<div id="projectInfo">
			Boydsprattgolfwear is a small business that has been selling clothing on ebay. Due to recent expansion and increased sales
			the website for this company also needs to be upgraded. I have developed an ecommerce site using php. The site is 
			designed to be simple and easy to use. This site developed with php provides simple ecommerce functionality for selling clothing online.
		</div>
    </li>
    
    <li>
      <div id="projectName"><h3>Marylou Fashion Boutique - Concept Design</h3></div>
		<div id="projectImage"><%= image_tag("marylou-concept-design.png", :alt => "No Image Available") %></div>
		<div id="projectInfo">
		This project was designed for a prototype for a small clothing boutique. It was designed for an expansion of a smaller company.
		It was programmed in PHP using a MySQL database. 		
		</div>
    </li>
    
    <li>
      <div id="projectName"><h3>Small Business Template Website - Clapham Removals</h3></div>
		<div id="projectImage"><%= image_tag("islingtonmoves-site.png", :alt => "No Image Available") %></div>
		<div id="projectInfo">
			A number of websites designed to show business information. Some functionality included being able to submit testimonials and take online quotes.
			The website was also integrated with photo galleries and mail capabilities.		
		</div>
    </li>
    
  </ul>





app/views/pages/resume.html.erb
    <%= render 'layouts/webhome' %>
<br />
<div id="info" class="resumeBox">
	<div id="title">
	   <h1>Mark G Howard</h1>
	   <div class="label">Web Developer</div>
	 </div>
	<div id="contactInfo">
	<h5>mobile</h5> 0422171468 <br />
	<h5>email</h5><a href="mailto:howieborn@gmail.com?Subject=Msg%20From%20Howie%20Born%20Website"> howieborn@gmail.com</a><br />
	<div class="button"><a href="MarkGHoward-CV.pdf">Download PDF</a></div>
	</div>
</div>

<div id="objective" class="resumeBox">
  <h4>Objective</h4>
  <div id="resText">To find employment which will allow me to gain experience and further my career in information technology as a web design and developer.</div>
</div>

<div id="qualifications" class="resumeBox">
  <h4>Qualifications</h4>
  <div id="resText"><h5>Bachelor Of Information Technology majoring in Information Systems</h5>
  2010	University Of Queensland</div>
</div>

<div id="empHistory" class="resumeBox">
	<h4>Work Experience</h4>
	<div id="resText">
		<div id="job">
			<span id="date">04/11 - present</span>
			<span id="locale">Boydspratt Golfwear Ocean Shores, NSW, Australia.</span>
			<br /><span id="position"> Web Site Developer - Ruby on Rails Programmer </span><br />
			<span id="description">Restructure and Implementation of an E-commerce System for a growing clothing business. Implemented in Ruby on Rails and MySql Database.</span>
		</div>
		<div id="job">
			<span id="date">01/09 - 05/09</span>
			<span id="locale">Boydspratt Golfwear Ocean Shores, NSW, Australia.</span>
			<br /><span id="position"> Web Site Design and PHP Application Development</span><br />
			<span id="description">Design, Implementation and Maintenance of an E-commerce System for a small business. Implemented in PHP and MySql.</span>
		</div>
		<div id="job">
		  	<span id="date">04/06 - 04/07</span>
		  	<span id="locale">Clapham Removals Pty Ltd, London, United Kingdom.</span>
		  	<br /><span id="position"> Web Site Developer / PHP Programmer</span><br />
		  	<span id="description">Design and Implementation of templates for small business websites. Maintenance of Websites. Implemented in PHP.</span>
		</div>
		<div id="job">
		  	<span id="date">06/01 - 07/02</span>
		  	<span id="locale">Hypersystems International Pty. Ltd. Brisbane, AUS</span>
		  	<br /><span id="position"> Application Programmer - Java Development on Linux </span><br />
		  	<span id="description">Analysis, Design and Implementation of Project Management and Communication solutions for a database driven web system. Platforms for Unix and Windows XP. Implemented in Java and JSP.</span>
		</div>
	</div>
</div>

<div id="skills" class="resumeBox">
	<h4>Skills</h4>
	<div id="resText">
		<div id="skill">
			<span id="heading">Analysis and Design</span><br />
			Compilation of functional requirements, dataflow diagrams and wireframes. Create applications using the software development lifecycle.
		</div>
		<div id="skill">
			<span id="heading">Programming</span><br />
			Ability to use Object Orientated Programming and MVC architecture to provide rapid development of applications. Understanding of server configuration and related technologies.
		</div>
		<div id="skill">
			<span id="heading">Web Development</span><br />
			Using Photoshop and other related software to create webpages. Use of CSS, HTML and javascript to provide validated websites, with an understanding of cross-browser configuration.</div>
	</div>
</div>

<div id="technical" class="resumeBox">
	<h4>Technical</h4>
	<div id="resText">
		<div id="tech">
			<div id="heading">Operating Systems</div><br />
			<ul>
			<li>Windows XP</li>
			<li>Vista</li>
			<li>Linux</li>
			<ul>
		</div>
		<div id="tech">
			<div id="heading">Programming</div><br />
			<ul>
			<li>PHP</li>
			<li>MVC</li>
			<li>Java</li>
			<li>Ruby</li>
			<li>SQL</li>
			<ul>
		</div>
		<div id="tech">
			<div id="heading">Applications</div><br />
			<ul>
			<li>Photoshop</li>
			<li>Dreamweaver</li>
			<li>Office</li>
			</ul>
		</div>
		<div id="tech">
			<div id="heading">Web Design Technologies</div><br />
			<ul>
			<li>HTML5</li>
			<li>CSS3</li>
			<li>javascript</li>
			<li>JQuery</li>
			<li>XML</li>
			<li>MySQL</li>
			<li>JSP</li>
			</ul>
		</div>
	</div>
</div>
<div id="references" class="resumeBox">
   <h4>References</h4>
	<div id="resText">
		<div id="ref1">
			<span id="name">Marylou Pratt</span><br />
			<span id="refPosition">Boydspratt Golfwear Director</span><br />
			<span id="refDetails">Phone: 0266801655 <br /> Email: <a href="mailto:mrlpratt725@gmail.com?Subject=Regarding%20Reference%20For%20Mark%20Howard">mrlpratt725@gmail.com</a></span>
		</div>
	</div
</div>
</div>

app/views/pages/webhome.html.erb
   <%= render 'layouts/webhome' %>
	<div class="leftCol">		  <div class="welcomeMsg"> <h3>Hello and Welcome...</h3>			<p>
		Hi, I'm a web designer, developer and programmer. I like to design websites using different and ever changing technologies.
		I like to solve problems relating to the web from interaction design and usability, to providing business and professional solutions for people and companies from all walks of life.
		<br /><br />
		This website has been specifically set up to provide resources and let prospective employers and clients view some of my current projects.</p>
	  </div  			</div>
		

app/views/pages/welcome.html.erb
<div class="welcomeContainer">
  <div class="welcomeContent">
	<div class="welcomeText">
	<% logo = image_tag("logo.png", :alt => "logo", :height => "100px", :class => "welcomeLogo") %>
    <%= link_to logo, root_path %>
		<div class="followme">
		<p><br><h3>Creative Consultant</h3><br>Follow me on:
		<ul>
		<li>Facebook</li>
		<li>Twitter</li>
		<li>etc..</li>
		</ul></p>
		</div>
	</div>
	<div class="welcomeWebhomeLink welcomeCircle">
	<center>
    <% webhome = image_tag("webhome.png", :class => "webhome") %>
    <%= link_to webhome, webhome_path %>
	</center>
	</div>
	<div class="welcomeMusichomeLink welcomeCircle">
	<center>
	<% musichome = image_tag("musichome.png", :class => "musichome") %>
    <%= link_to musichome, musichome_path %>
	</center>
	</div>